Fix ReferenceError on _imposter
Variable imposter wasn't being recognized inside _imposter, causing fail on render the /imposters route. 

ReferenceError: /.../.../mock-server/node_modules/mountebank/src/views/imposters.ejs:34
    32| 
    33|   <% imposters.forEach(imposter => { %>
 >> 34|   <%- include('_imposter') -%>
    35|   <% }); -%>
    36| </table>
    37| 

/.../.../mock-server/node_modules/mountebank/src/views/_imposter.ejs:1
 >> 1| <tr id='imposter-<%= imposter.port %>'>
    2|   <td style='width: 15em;'><a href='<%= imposter._links.self.href %>'>
    3|     <%= imposter.name || imposter.protocol + ':' + imposter.port %>
    4|   </a></td>

imposter is not defined
    at eval (eval at compile (/.../.../mock-server/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:11:26)
    at _imposter (/.../.../mock-server/node_modules/ejs/lib/ejs.js:692:17)
    at include (/.../.../mock-server/node_modules/ejs/lib/ejs.js:690:39)
    at eval (eval at compile (/.../.../mock-server/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:29:17)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/.../XXX/mock-server/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:26:18)
    at imposters (/.../XXX/mock-server/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/.../XXX/mock-server/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/.../.../mock-server/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/t.cassim