Fix ReferenceError on _imposter Variable imposter wasn't being recognized inside _imposter, causing fail on render the /imposters route.
ReferenceError: /.../.../mock-server/node_modules/mountebank/src/views/imposters.ejs:34
32|
33| <% imposters.forEach(imposter => { %>

34| <%- include('_imposter') -%>
35| <% }); -%>
36|
37|

/.../.../mock-server/node_modules/mountebank/src/views/_imposter.ejs:1

1|
2|
3| <%= imposter.name || imposter.protocol + ':' + imposter.port %>
4|

imposter is not defined
at eval (eval at compile (/.../.../mock-server/node_modules/ejs/lib/ejs.js:662:12), :11:26)
at _imposter (/.../.../mock-server/node_modules/ejs/lib/ejs.js:692:17)
at include (/.../.../mock-server/node_modules/ejs/lib/ejs.js:690:39)
at eval (eval at compile (/.../.../mock-server/node_modules/ejs/lib/ejs.js:662:12), :29:17)
at Array.forEach ()
at eval (eval at compile (/.../.../mock-server/node_modules/ejs/lib/ejs.js:662:12), :26:18)
at imposters (/.../.../mock-server/node_modules/ejs/lib/ejs.js:692:17)
at tryHandleCache (/.../.../mock-server/node_modules/ejs/lib/ejs.js:272:36)
at View.exports.renderFile [as engine] (/.../.../mock-server/node_modules/ejs/lib/ejs.js:489:10)
at View.render (/.../...